# -*- coding: utf-8 -*-
"""flask_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mqHX7HqxZzzNPhVBW37PZTf6rxpoeEez
"""

!pip install flask_cors

from flask import Flask, jsonify
from flask_cors import CORS
from google.colab import drive
import json

# Monta o Google Drive (para acesso a arquivos)
drive.mount('/content/drive')

app = Flask(__name__)
CORS(app)  # Permite CORS para todas as rotas

@app.route('/index', methods=['GET'])
def index():
    return "Hello World", 200

# Adiciona uma rota para retornar dados JSON (exemplo de leitura de arquivo JSON)
@app.route('/data', methods=['GET'])
def get_data():
    try:
        # Supondo que o arquivo JSON esteja no Google Drive
        with open('/content/drive/My Drive/path_to_your_file.json', 'r') as file:
            data = file.read()
        return jsonify(json.loads(data))
    except FileNotFoundError:
        return jsonify({"error": "File not found"}), 404
    except json.JSONDecodeError:
        return jsonify({"error": "Error decoding JSON"}), 400

if __name__ == '__main__':
    app.run(port=5000)

!pip install flask-ngrok
from flask_ngrok import run_with_ngrok

# Inicia o Flask com ngrok
run_with_ngrok(app)
app.run()